### ISSUE TITLE
when logged in with and admin account, all pages crash

### ISSUE THREAD

**Issue by petelliott** [Petelliott/CMPUT404-project#90]
when logged in with an admin account, (that has no author) the template rendering fails. please account for users without authors.

**Comment by colinchoix** [comment]
Just wondering before I work on this, is there a reason we don't just give the super admin an entry in the author table? If the superadmin is expected to interact with the site, this seems like a simpler solution

**Comment by petelliott** [comment]
Because there can be multiple admins and no way to enforce this. And it is
no harder to check than if the user is authenticated with Author.from_user()
